# Generated by Django 5.2.4 on 2025-12-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
